//
// Created by TheDaChicken on 9/2/2024.
//

#ifndef NRSC5_GUI_LIB_UTILS_ERROR_H_
#define NRSC5_GUI_LIB_UTILS_ERROR_H_

#define NRSC5_TUNER_ACTIVE (0)
#define NRSC5_TUNER_STARTING (1)
#define NRSC5_TUNER_STOPPING (2)
#define NRSC5_TUNER_NOT_ACTIVE (3)
#define NRSC5_TUNER_DEVICE_PENDING (4)

#define NRSC5_DEFAULT_ERROR (-1)

#define NRSC5_SDR_NO_DEVICE (-2)
#define NRSC5_SDR_BAD_COMMUNICATION (-3)
#define NRSC5_SDR_BAD_SAMPLE_RATE (-4)
#define NRSC5_SDR_BAD_GAIN (-8)
#define NRSC5_SDR_BAD_FREQUENCY (-16)
#define NRSC5_SDR_BAD_BANDWIDTH (-32)

#define NRSC5_AUDIO_NO_DEVICE (-1)

#endif //NRSC5_GUI_LIB_UTILS_ERROR_H_
